version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db_sgc
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3360:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

